### ISSUE TITLE
Si el problema no existe, falla

### ISSUE THREAD

**Issue by penicolas** [penicolas/project-euler#12]
Ante problemas que no están falla:

```
$ projecteuler.exe -p 400
Traceback (most recent call last):
  File "C:\Python35\Scripts\projecteuler-script.py", line 11, in <module>
    load_entry_point('projecteuler', 'console_scripts', 'projecteuler')()
  File "d:\users\pnicolas\code\github\project-euler\projecteuler\projecteuler.py", line 88, in main
    result, totaltime = exec_problem(number)
  File "d:\users\pnicolas\code\github\project-euler\projecteuler\projecteuler.py", line 42, in exec_problem
    exec(fs.format(pmodule), globals(), ns)
  File "<string>", line 1, in <module>
ImportError: cannot import name 'r0400'
```

**Comment by penicolas** [comment]
Bien, si pongo el try-except que había puesto, cualquier fallo en el programa se trata como bueno...
